"""Render state -> README.md (active) and README-Inactive.md (closed)."""
from __future__ import annotations
from datetime import date, datetime, timezone

CATEGORY_ORDER = [
    ("Software Engineering", "💻"),
    ("Quantitative Finance", "📈"),
    ("Data Science, AI & ML", "🤖"),
    ("Hardware Engineering", "🔧"),
    ("Product Management", "📱"),
]


def _age(first_seen: str, today: date) -> str:
    try:
        first = date.fromisoformat(first_seen)
    except ValueError:
        return "?"
    days = (today - first).days
    if days <= 0:
        return "🆕"
    if days < 30:
        return f"{days}d"
    if days < 365:
        return f"{days // 30}mo"
    return f"{days // 365}y"


def _anchor(name: str) -> str:
    return name.lower().replace(" ", "-").replace(",", "").replace("&", "")


def _row(r: dict, today: date) -> str:
    title = r["title"].replace("|", "\\|")
    loc = r["location"].replace("|", "\\|")
    apply_cell = f"[Apply]({r['url']})" if r.get("url") else "—"
    return (f"| **{r['company']}** | {title} | {loc} | {apply_cell} "
            f"| {_age(r['first_seen'], today)} |")


def render_active(state: dict, *, today: date | None = None) -> str:
    today = today or datetime.now(timezone.utc).date()
    active = [r for r in state.values() if r.get("active", True)]
    counts = {}
    for r in active:
        counts[r["category"]] = counts.get(r["category"], 0) + 1

    L = ["# Internships in EMEA & APAC 2027 🌍🌏", ""]
    L.append("A community-maintained, auto-aggregated list of **student "
             "internships across EMEA & APAC** — software, quant, data/ML, "
             "hardware, and product roles for any 2027 season. Covers London, "
             "Dublin, Amsterdam, Berlin, Paris, Zurich, Dubai, Tel Aviv and the "
             "wider EMEA region, plus Singapore, Hong Kong, Tokyo, Seoul, "
             "Shanghai, Bengaluru, SE Asia and Oceania.")
    L.append("")
    L.append(f"**{len(active)} active roles** · updated automatically · "
             "contribute via [issue](../../issues/new/choose)")
    L.append("")
    idx = []
    for name, emoji in CATEGORY_ORDER:
        idx.append(f"{emoji} [{name}](#{_anchor(name)}) ({counts.get(name, 0)})")
    L.append(" · ".join(idx))
    L.append("")
    L.append("> 🆕 posted today · `Nd` = days listed · 🔒 closed roles live in "
             "[README-Inactive.md](README-Inactive.md) · 🗂️ can't-auto-scrape "
             "employers are in the [Company Directory](DIRECTORY.md)")
    L.append("")
    L.append("---")
    L.append("")
    for name, emoji in CATEGORY_ORDER:
        rows = [r for r in active if r["category"] == name]
        if not rows:
            continue
        rows.sort(key=lambda r: (r["first_seen"], r["company"]), reverse=True)
        L.append(f"## {emoji} {name}")
        L.append("")
        L.append("| Company | Role | Location | Application | Age |")
        L.append("| --- | --- | --- | --- | --- |")
        L += [_row(r, today) for r in rows]
        L.append("")
    L.append("---")
    L.append("")
    L.append("_Auto-aggregated daily from upstream community lists "
             "([speedyapply](https://github.com/speedyapply/2027-SWE-College-Jobs), "
             "[Campus2026](https://github.com/namewyf/Campus2026)) plus direct ATS "
             "feeds and community submissions, then filtered to EMEA/APAC 2027 "
             "internships and de-duplicated. Do not edit this file by hand — edit "
             "`data/sources.json` / `data/registry.json` and let the updater "
             "regenerate it._")
    L.append("")
    return "\n".join(L)


def render_inactive(state: dict, *, today: date | None = None) -> str:
    today = today or datetime.now(timezone.utc).date()
    closed = [r for r in state.values() if not r.get("active", True)]
    L = ["# Closed / Archived Roles 🔒", ""]
    L.append(f"Roles no longer active ({len(closed)}). Kept for reference; never "
             "deleted.")
    L.append("")
    if not closed:
        L.append("_None yet._")
        L.append("")
        return "\n".join(L)
    closed.sort(key=lambda r: r.get("last_seen", ""), reverse=True)
    L.append("| Company | Role | Location | Link | Closed because | Last seen |")
    L.append("| --- | --- | --- | --- | --- | --- |")
    reason_label = {"link_dead": "link dead", "stale_year": "previous year"}
    for r in closed:
        title = r["title"].replace("|", "\\|")
        loc = r["location"].replace("|", "\\|")
        link = f"[link]({r['url']})" if r.get("url") else "—"
        reason = reason_label.get(r.get("close_reason"), r.get("close_reason") or "—")
        L.append(f"| **{r['company']}** | {title} | {loc} | {link} | {reason} "
                 f"| {r.get('last_seen', '?')} |")
    L.append("")
    return "\n".join(L)


def render_directory(watchlist: list[dict]) -> str:
    """Render watchlist.json -> DIRECTORY.md (browse links, grouped by region)."""
    L = ["# Company Directory 🗂️", ""]
    L.append("Employers with strong APAC internship programs whose postings live "
             "on **bespoke career portals we don't auto-scrape** (native Asian "
             "giants, S&P 500 APAC branches, login/region-locked sites). These are "
             "curated **browse-here** links — open them and search for interns "
             "directly. Links are liveness-checked.")
    L.append("")
    L.append(f"**{len(watchlist)} employers.** Missing one? Add it — see "
             "[CONTRIBUTING](CONTRIBUTING.md).")
    L.append("")
    # Bucket into clean macro-regions by keyword, instead of one header per
    # unique location string.
    BUCKETS = [
        ("Hong Kong", ["hong kong"]),
        ("Mainland China", ["shanghai", "beijing", "shenzhen", "hangzhou",
                             "guangzhou"]),
        ("Korea", ["seoul", "suwon", "icheon", "jeju"]),
        ("Japan", ["tokyo", "kyoto"]),
        ("Southeast Asia", ["singapore", "kuala lumpur", "jakarta", "bangkok",
                             "manila", "penang"]),
        ("South Asia", ["bengaluru", "hyderabad", "gurugram", "noida", "india"]),
        ("Oceania", ["sydney", "melbourne"]),
    ]

    def bucket_of(region: str) -> str:
        r = region.lower()
        for name, keys in BUCKETS:
            if any(k in r for k in keys):
                return name
        return "Other / Multi-region"

    order = [b[0] for b in BUCKETS] + ["Other / Multi-region"]
    by_region: dict[str, list[dict]] = {}
    for e in watchlist:
        by_region.setdefault(bucket_of(e.get("region", "")), []).append(e)
    for region in order:
        if region not in by_region:
            continue
        L.append(f"### {region}")
        L.append("")
        L.append("| Company | Careers link | Notes |")
        L.append("| --- | --- | --- |")
        for e in sorted(by_region[region], key=lambda x: x["company"]):
            note = e.get("note", "")
            L.append(f"| **{e['company']}** | [Open]({e['url']}) | {note} |")
        L.append("")
    return "\n".join(L)
